### ISSUE TITLE
coloring of text in grey boxes

### ISSUE THREAD

**Issue by iamm28** [learn-co-students/python-intro-to-strings-data-science-pilot#10]
I'm not totally clear on the pattern of what is red, blue or black. Looks like red might be text and black is output/responses

**Comment by iamm28** [comment]
just realized there is more than one blue/green in the next lesson so now it is making more sense

**Comment by tkoar** [comment]
I've added a note and comments in the first few examples to mark the input. This should add clarity for viewing the readme in markdown. This change will be merged in.
