### ISSUE TITLE
Small note

### ISSUE THREAD

**Issue by misslesliehsu** [learn-co-students/python-intro-to-strings-data-science-pilot#7]
Would be easier to add the idea of sequence when explaining the below (e.g. "followed by", or using numbers")

We can operate on a datatype with the following format:

datatype
dot
method name
parentheses_

**Comment by tkoar** [comment]
changed the format to hopefully add clarity -- please note the examples following that should ultimately add more context and clarify the datatype-dot-method_name-parentheses format. This change will be merged in
