### ISSUE TITLE
Nitpicky Grammar Stuff

### ISSUE THREAD

**Issue by ddbrennan** [learn-co-students/python-intro-to-strings-data-science-pilot#8]
Lots of unnecessary 'And's starting sentences. 

Don't need comma after 'Song Lyrics'

Also, every time there's a phrase like "Here's an example of X:" I expect a colon but it's always a period.

In Discovering New Methods "let's follow ITS stern directions..."

**Comment by tkoar** [comment]
edited some language to correct the grammar. will be fixed in merge
